apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice-deployment
  labels:
    app: simpletimeservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: nishant4028/simpletimeservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
        effect: "NoSchedule"
